sonar.projectKey=anime-backend
sonar.projectName=Anime App - Backend
sonar.projectVersion=2.0.0
sonar.sources=backend
sonar.exclusions=**/node_modules/**,**/openapi.json,**/.env*
sonar.language=js
sonar.javascript.file.suffixes=.js
sonar.host.url=http://localhost:9000
sonar.login=sqp_53936935218f70a329e32e8867efb1535e8f4713
sonar.sourceEncoding=UTF-8